---
title: "Plots"
author: "Caroline & Julia"
date: "12/7/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
##Wrangling School Closures DF

sf <- stamp("02-2019", orders = "my") 
closures_df$Date <- lubridate::dmy(closures_df$Date)
closures_df <- closures_df %>%
    mutate(month_year = sf(Date)) %>%
    filter(month_year != "02-2020")

is.factor(closures_df$Status)
table(closures_df$Status)
closures_df$Status <- factor(closures_df$Status, levels = c("Closed due to COVID-19", "Partially open", "Fully open", "Academic break"))
closures_df$test <- as.numeric(closures_df$Status)
nfactor <- length(levels(closures_df$Status))
foo <- brewer.pal(n = nfactor, name = "Set1")
names(foo) <- levels(closures_df$Status)
```
 



```{r}
##Wrangling Teacher vaccination data
names(teacher_vac_df)[names(teacher_vac_df) == "Vaccination data reference date"] <- "Date"
names(teacher_vac_df)[names(teacher_vac_df) == "Teacher prioritization in vaccination plans"] <- "vac_priority_status"

teacher_vac_df <- teacher_vac_df %>% 
  drop_na("vac_priority_status")

is.factor(teacher_vac_df$vac_priority_status)
table(teacher_vac_df$vac_priority_status)
teacher_vac_df$vac_priority_status<- factor(teacher_vac_df$vac_priority_status, levels = c("Group 1", "Group 2", "Group 3 or lower", "Not prioritised in any group", "Not specified", "No available data"))
```



```{r}
#Wrangling cumulative_closure_df
head(cumulative_closure_df)

names(cumulative_closure_df)[names( cumulative_closure_df) == "UNICEF Country"] <- "country"
names(cumulative_closure_df)[names( cumulative_closure_df) == "UNICEF Region"] <- "region"
names(cumulative_closure_df)[names( cumulative_closure_df) == "Income Group"] <- "income_group"
names(cumulative_closure_df)[names( cumulative_closure_df) == "Days: Academic break"] <- "academic_break"
names(cumulative_closure_df)[names( cumulative_closure_df) == "Days: Fully closed"] <- "fully_closed"
names(cumulative_closure_df)[names( cumulative_closure_df) == "Days: Fully open"] <- "fully_open"
names(cumulative_closure_df)[names( cumulative_closure_df) == "Days:  Partially closed"] <- "partially_closed"
names(cumulative_closure_df)[names( cumulative_closure_df) == "Instruction Days"] <- "instructions_date"
names(cumulative_closure_df)[names( cumulative_closure_df) == "Pre-primary"] <- "pre_primary"
names(cumulative_closure_df)[names( cumulative_closure_df) == "Lower Secondary"] <- "lower_secondary"
names(cumulative_closure_df)[names( cumulative_closure_df) == "Upper Secondary"] <- "upper_secondary"
```


```{r}
##Wrangling connectivity data
head(Total_school_connectivity_df)

names(Total_school_connectivity_df)[names(Total_school_connectivity_df) == "Countries and areas"] <- "country"
names(Total_school_connectivity_df)[names(Total_school_connectivity_df) == "Sub-region"] <- "sub_region"
names(Total_school_connectivity_df)[names(Total_school_connectivity_df) == "Income Group"] <- "income_group"
names(Total_school_connectivity_df)[names(Total_school_connectivity_df) == "...12"] <- "Date"


```



```{r}
#Wrangling Vaccination rates
head(teacher_vac_df)
names(teacher_vac_df)[names(teacher_vac_df) == "Country"] <- "country"
names(teacher_vac_df)[names(teacher_vac_df) == "% of teachers with at least one dosis"] <- "first_shot"
names(teacher_vac_df)[names(teacher_vac_df) == "% of teachers fully vaccinated"] <- "second_shot"
```


```{r}
#Join data frames and create complete_schools_df
complete_schools_df <- dplyr::left_join(cumulative_closure_df,
Total_school_connectivity_df, 
  by = "ISO3" ## Be specific about the joining column
  ) %>%
select(ISO3, country.x, region, income_group.x, academic_break, fully_closed, fully_open, partially_closed, instructions_date,
       pre_primary, Primary, lower_secondary, upper_secondary, Total)

names(complete_schools_df)[names(complete_schools_df) == "income_group.x"] <- "income_group"
names(complete_schools_df)[names(complete_schools_df) == "country.x"] <- "country"
names(complete_schools_df)[names(complete_schools_df) == "Total"] <- "internet_access"
names(complete_schools_df)[names(complete_schools_df) == "Primary"] <- "primary"


complete_schools_df <- dplyr::left_join(complete_schools_df,
teacher_vac_df, 
  by = "country" 
  ) %>%
  select(-c(first_shot, second_shot, Date))

head(complete_schools_df)

complete_schools_df <- complete_schools_df %>%
  mutate(., total_students = pre_primary + primary + lower_secondary + upper_secondary, .keep = "all")
complete_schools_df

complete_schools_df 
is.factor(complete_schools_df$vac_priority_status)
table(complete_schools_df$vac_priority_status)


table(complete_schools_df$region)
```


```{r}
#Wrangling UNESCO Database for distance learning 

names(UNESCO_school_closures_df)[names(UNESCO_school_closures_df) == "Country ID"] <-
  "ISO3"
names(UNESCO_school_closures_df)[names(UNESCO_school_closures_df) == "Country"] <-
  "country"
names(UNESCO_school_closures_df)[names(UNESCO_school_closures_df) == "Region 1"] <-
  "region"
names(UNESCO_school_closures_df)[names(UNESCO_school_closures_df) == "Status"] <-
  "status"
names(UNESCO_school_closures_df)[names(UNESCO_school_closures_df) == "Enrolment (Pre-Primary to Tertiary)"] <-
  "enrollment"
names(UNESCO_school_closures_df)[names(UNESCO_school_closures_df) == "Teachers (Pre-Primary to Upper Secondary)"] <-
  "teachers_number"
names(UNESCO_school_closures_df)[names(UNESCO_school_closures_df) == "Distance learning modalities (TV)"] <-
  "tv"
names(UNESCO_school_closures_df)[names(UNESCO_school_closures_df) == "Distance learning modalities (Radio)"] <-
  "radio"
names(UNESCO_school_closures_df)[names(UNESCO_school_closures_df) == "Distance learning modalities (Online)"] <-
  "online_learning"
names(UNESCO_school_closures_df)[names(UNESCO_school_closures_df) == "Distance learning modalities (Global)"] <-
  "distance_learning"
names(UNESCO_school_closures_df)[names(UNESCO_school_closures_df) == "Weeks partially open"] <-
  "weeks_partially_closed"
names(UNESCO_school_closures_df)[names(UNESCO_school_closures_df) == "Weeks fully closed"] <-
  "weeks_fully_closed"                                   
head(UNESCO_school_closures_df)    


UNESCO_school_closures_df <- UNESCO_school_closures_df %>%
  select(., Date, ISO3, country, region, status, enrollment, teachers_number, tv, radio, online_learning, distance_learning, weeks_partially_closed, weeks_fully_closed)


UNESCO_school_closures_df$Date <- lubridate::ymd(UNESCO_school_closures_df$Date)

typeof(UNESCO_school_closures_df$Date)
```



```{r}
#Adding TV and Radio data 
unesco_reduced <- filter(UNESCO_school_closures_df, UNESCO_school_closures_df$Date == "2021-10-31")%>%
  select(., tv, radio, online_learning, distance_learning, ISO3)


complete_schools_df <- dplyr::left_join(complete_schools_df,
unesco_reduced, 
  by = "ISO3" 
  ) 


complete_schools_df <- complete_schools_df %>%
  drop_na("vac_priority_status")

complete_schools_df <- complete_schools_df %>%
  mutate(total_students2 = total_students/1000000) %>%
  mutate(total_students2 = round(total_students2, 2))

```

```{r}
#creating a table for closures_df

closures_table_df <- select(complete_schools_df, c(country, region, 
                          fully_closed, partially_closed, internet_access,
                          vac_priority_status, total_students, tv, radio, 
                          online_learning, distance_learning))

```

<<<<<<< Updated upstream

```{r}
#Data wrangling for schoool closure map

# Creating a month_year column
sf <- stamp("02-2019", orders = "my") 
closures_df$Date <- lubridate::dmy(closures_df$Date)
closures_df <- closures_df %>%
  mutate(month_year = sf(Date)) %>%
  filter(month_year != "02-2020")

# Factoring Status
is.factor(closures_df$Status)
table(closures_df$Status)
closures_df$Status <- factor(closures_df$Status, levels = c("Closed due to COVID-19", "Partially open", "Fully open",
                                                            "Academic break"))
closures_df$test <- as.numeric(closures_df$Status)
nfactor <- length(levels(closures_df$Status))
foo <- brewer.pal(n = nfactor, name = "Set1")
names(foo) <- levels(closures_df$Status)
```


=======
>>>>>>> Stashed changes
```{r}
#functions for graphs

Z_Breaks = function(n){
CUTS = seq(0,1,length.out=n+1)
rep(CUTS,ifelse(CUTS %in% 0:1,1,2))
}

```



