install.packages("shinydashboard")

##Defining shiny dashboard components and publishing
```{r}
library(shinydashboard)
library(shiny)

ui <- fluidPage(
<<<<<<< HEAD
  titlePanel("Basic dashboard"),
=======
  titlePanel("COVID School Closures Dashboard"),
  # fluidRow(
  #   column(3,
  #   )
  #   ),
>>>>>>> parent of b72d40f... shiny updates
  sidebarLayout(
<<<<<<< HEAD
    sidebarPanel("sidebar panel"),
    mainPanel("main panel")
=======
    sidebarPanel(
      helpText("sidebar panel"),
      
      selectInput("month_select", label = "Select the Month",
          choices = c("02-2020","03-2020","04-2020",
                      "05-2020","06-2020","07-2020",
                      "08-2020","09-2020","10-2020",
                      "11-2020","12-2020","01-2021",
                      "02-2021","03-2021","04-2021",
                      "05-2021","06-2021","07-2021",
                      "08-2021","09-2021","10-2021",
                      "11-2021"),
          selected = "02-2020"),
    ),
<<<<<<< HEAD
    mainPanel(
      plotlyOutput("fig", width = "100%")
      )
>>>>>>> parent of 6d2ea44... another update to shiny script
  ))


server <- function(input, output) {
  # set.seed(122)
  # histdata <- rnorm(500)
  # 
  # output$plot1 <- renderPlot({
  #   data <- histdata[seq_len(input$slider)]
  #   hist(data)
  # })
=======
    mainPanel(plotlyOutput("fig"))
  ))



server <- function(input, output) {
  output$fig <- renderPlotly({
   
  filteredData <- filter(closures_df, month_year == input$month_select)
  
  fig <- plot_ly(filteredData, 
         type='choropleth', 
         locations= ~ISO, 
         z=closures_test$test, 
         text=closures_test$Country,
         colorscale=colorScale,
  colorbar=list(tickvals=1:nfactor, ticktext=names(foo))
  )
  
  fig
   })
>>>>>>> parent of b72d40f... shiny updates
}

shinyApp(ui, server)

```

## Dataframes
```{r}
library(tidyverse)
library(readr)
library(lubridate)
closures_df <- read_csv("covid_impact_education.csv")

view(closures_df)

# Creating a month_year column
sf <- stamp("02-2019", orders = "my") 

closures_df$Date <- lubridate::dmy(closures_df$Date)

closures_df <- closures_df %>%
  mutate(month_year = sf(Date))


is.factor(closures_df$Status)
table(closures_df$Status)
closures_df$Status <- factor(closures_df$Status, levels = c("Closed due to COVID-19 ", "Partially open", "Fully open", "Academic break"))






```

## Plots
```{r}
library(ggplot2)
library(ggpubr)
library(plotly)
library("devtools")

install_github("ropensci/plotly")

py <- plotly(username="rAPI", key="yu680v5eii", base_url="https://plot.ly")

source("plotlyGraphWidget.R")


#Output Graph Function
graphOutput <- function(inputId, width="100%", height="550px") {
    tagList(
        singleton(tags$head(
            tags$script(src="plotlyGraphWidget.js")
        )),
       tags$iframe(id=inputId, src="https://plot.ly/~playground/7.embed",
       class="graphs", style="border:none;", seamless=TRUE, width=width, height=height)
    )
}

renderGraph <- function(expr, env=parent.frame(), quoted=FALSE) {
    ## This gets called when inputs change --
    ## Place data wrangling code in here
    ## and pass the result to the client
    ## to be graphed.


	installExprFunction(expr, "func", env, quoted)

    function(){
        data = func();
        ## data is the state of the widgets: see server.R
        ## this function returns a list of named lists that descripe
        ## valid postMessage commands to be sent to the embedded iframe.
        ## see binding.renderValue for the receiving JS side of this function
        ## and https://github.com/plotly/Embed-API for more about the postMessage
        ## graph messages
        return(data)

    }
}

# # light grey boundaries
# l <- list(color = toRGB("grey"), width = 0.5)
# 
# # specify map projection/options
# g <- list(
#   showframe = FALSE,
#   showcoastlines = FALSE,
#   projection = list(type = 'Mercator')
# )

closures_test <- closures_df %>%
  dplyr::filter(month_year == "11-2020")

# light grey boundaries
l <- list(color = toRGB("grey"), width = 0.5)

<<<<<<< HEAD
# specify map projection/options
g <- list(
  showframe = FALSE,
  showcoastlines = FALSE,
  projection = list(type = 'Mercator')
=======
fig <- plot_ly(closures_test, 
               type='choropleth', 
               locations= ~ISO, 
               z=closures_test$test, 
               text=closures_test$Country,
               colorscale=colorScale,
  colorbar=list(tickvals=1:nfactor, ticktext=names(foo))
>>>>>>> parent of b72d40f... shiny updates
)

closures_test <- closures_df %>%
  dplyr::filter(month_year == "01-2021")

fig <- plot_geo(closures_df)

fig <- plot_ly(closures_test, type='choropleth', locations=closures_test$ISO, z=closures_test$Status, text=closures_test$Country)

fig
fig <- fig %>% add_trace(
    z = ~Status, color = ~Status, 
    text = ~Country, locations = ~ISO, marker = list(line = l)
  )

fig <- fig %>% colorbar(title = 'GDP Billions US$', tickprefix = '$')
fig <- fig %>% layout(
    title = '2014 Global GDP<br>Source:<a href="https://www.cia.gov/library/publications/the-world-factbook/fields/2195.html">CIA World Factbook</a>',
    geo = g
  )



```
